version: '3.1'

services:
  inventory-db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env.devdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    restart: always

  inventory-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    depends_on:
      inventory-db:
        condition: service_healthy
    restart: always
    environment:
      - ENV_FILE_PATH=../.env.dev

volumes:
  db_data:
