FROM python:3.10-slim

COPY . /code
WORKDIR /code/api

RUN pip install --no-cache-dir --upgrade -r ../requirements.txt

EXPOSE 8000

ENV ENV_FILE_PATH=../.env.prod

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]